import ClassicProfessional from './ClassicProfessional';
import ModernTwoColumn from './ModernTwoColumn';
import ExecutiveTimeline from './ExecutiveTimeline';
import CreativePortfolio from './CreativePortfolio';
import MinimalistClean from './MinimalistClean';
import TechDeveloper from './TechDeveloper';
import ATSMaximizer from './ATSMaximizer';

export const TEMPLATE_REGISTRY = [
  {
    id: "classic-professional",
    name: "Classic Professional",
    description: "Clean, ATS-optimized single-column layout. Works for all industries.",
    tier: "free",
    category: ["all", "corporate", "finance", "healthcare"],
    atsScore: 98,
    layout: "single-column",
    accentColorDefault: "#2563EB",
    supportedSections: ["summary", "experience", "education", "skills", "certifications"],
    thumbnail: "https://placehold.co/400x500/2563EB/FFFFFF?text=Classic+Professional",
    component: ClassicProfessional,
  },
  {
    id: "modern-two-column",
    name: "Modern Two-Column",
    description: "30/70 left-sidebar layout: skills, contact, education in sidebar; experience in main column.",
    tier: "free",
    category: ["all", "marketing", "sales"],
    atsScore: 72,
    layout: "two-column",
    accentColorDefault: "#7C3AED",
    supportedSections: ["summary", "experience", "education", "skills", "certifications", "projects"],
    thumbnail: "https://placehold.co/400x500/7C3AED/FFFFFF?text=Modern+Two+Column",
    component: ModernTwoColumn,
  },
  {
    id: "executive-timeline",
    name: "Executive Timeline",
    description: "Single column with left-border timeline for experience entries.",
    tier: "free",
    category: ["senior", "corporate", "consulting"],
    atsScore: 90,
    layout: "single-column-timeline",
    accentColorDefault: "#1E293B",
    supportedSections: ["summary", "experience", "education", "skills", "certifications"],
    thumbnail: "https://placehold.co/400x500/1E293B/FFFFFF?text=Executive+Timeline",
    component: ExecutiveTimeline,
  },
  {
    id: "creative-portfolio",
    name: "Creative Portfolio",
    description: "Bold full-width color header block; asymmetric two-panel layout.",
    tier: "free",
    category: ["creative", "design", "marketing"],
    atsScore: 65,
    layout: "asymmetric",
    accentColorDefault: "#EC4899",
    supportedSections: ["summary", "experience", "education", "skills", "projects"],
    thumbnail: "https://placehold.co/400x500/EC4899/FFFFFF?text=Creative+Portfolio",
    component: CreativePortfolio,
  },
  {
    id: "minimalist-clean",
    name: "Minimalist Clean",
    description: "Maximum white space; narrow centered column.",
    tier: "free",
    category: ["academia", "research", "startups"],
    atsScore: 96,
    layout: "centered-column",
    accentColorDefault: "#111827",
    supportedSections: ["summary", "experience", "education", "skills", "certifications"],
    thumbnail: "https://placehold.co/400x500/111827/FFFFFF?text=Minimalist+Clean",
    component: MinimalistClean,
  },
  {
    id: "tech-developer",
    name: "Tech Developer",
    description: "Monospace font accents, inline code-style skill tags.",
    tier: "premium",
    category: ["tech", "engineering", "data"],
    atsScore: 88,
    layout: "single-column",
    accentColorDefault: "#0D9488",
    supportedSections: ["summary", "experience", "education", "skills", "projects"],
    thumbnail: "https://placehold.co/400x500/0D9488/FFFFFF?text=Tech+Developer",
    component: TechDeveloper,
  },
  {
    id: "ats-maximizer",
    name: "ATS Maximizer",
    description: "Zero design — pure ATS optimization mode.",
    tier: "free",
    category: ["all"],
    atsScore: 100,
    layout: "pure-text",
    accentColorDefault: "#000000",
    supportedSections: ["summary", "experience", "education", "skills", "certifications", "projects"],
    thumbnail: "https://placehold.co/400x500/000000/FFFFFF?text=ATS+Maximizer",
    component: ATSMaximizer,
  }
];
